name=STM32duino ILPS22QS
version=1.1.1
author=STMicroelectronics
maintainer=stm32duino
sentence=Nano pressure sensor with I3C support.
paragraph=This library provides Arduino support for the Ultra Low Power ILPS22QS over I2C, SPI, or I3C for STM32 boards.
category=Sensors
url=https://github.com/stm32duino/ILPS22QS
architectures=*
